feat: add vite specific tags
adonisjs/view pull request #18
Opened 2022-10-26 21:53 UTC by Julien-R44

- Add `@vite` tag that which will inject the @vite/client script needed by the HMR
- Add `@viteReactRefresh` tag that will inject the script needed for HMR to work with React, as asked to do here : https://vitejs.dev/guide/backend-integration.html

The tests will fail because it will be necessary to merge and update @adonisjs/application and @adonisjs/core

Related to https://github.com/adonisjs/core/issues/3953

2022-10-29 17:40 UTC, RomainLanz requested changes

2022-10-29 17:40 UTC, RomainLanz commented on src/Bindings/Vite.ts
> +import { ViewContract } from '@ioc:Adonis/Core/View'
```suggestion
import type { ViewContract } from '@ioc:Adonis/Core/View'
```

2022-10-29 17:40 UTC, RomainLanz commented on providers/ViewProvider.ts
> +import { defineViteDriverBindings } from '../src/Bindings/Vite'
This import should be before types imports

2022-10-29 21:38 UTC, Julien-R44 commented
Still needs to merge and update "application" and "core" to see green tests

2022-11-26 20:59 UTC, Julien-R44 commented
Ready to merge

2022-11-28 17:07 UTC, merged